### ISSUE TITLE
Setting behaviour in controller

### ISSUE THREAD

**Issue by elfarqy** [haqqi/yii2-advanced-api#2]
Hal ini meliputi 
`contentNegotiator` - format yang akan digunakan
`ApiKey` - apikey authentification
`AccessToken` - untuk melakukan pengecekan tiap device yang login

**Comment by haqqi** [comment]
@elfarqy Untuk yang sekarang, semua masuk di behavior authenticator yang menggunakan CompositeAuth. Bisa dicek di Module.php untuk v1, gimana caranya masukkan via dependency container.

**Comment by haqqi** [comment]
@elfarqy 
untuk `contentNegotiator` sudah disetup di rest\Controller. Jadi gak perlu lagi. Basically akan menerima request sesuai permintaa, apakah xml atau json.
untuk `apiKey` masih tidak diperlukan di template ini.
untuk `accessToken` sudah dipasang di bootstraping via dependency injection container.
