### ISSUE TITLE
Create RegisterUserForm

### ISSUE THREAD

**Issue by elfarqy** [haqqi/yii2-advanced-api#3]
`RegisterUserForm` digunakan untuk menangani field pada register

**Comment by elfarqy** [comment]
Form ini harusnya configurable, untuk mengakomodir user akan di force login setelah ter registrasi atau tidak.

**Comment by haqqi** [comment]
@elfarqy Contoh untuk configurasi bisa dilihat di repo orang ini https://packagist.org/packages/nenad/yii2-advanced-template

**Comment by haqqi** [comment]
@haqqi Beda donk. Itu tadi, mesti ada konfigurasi untuk aktivasi user atau nggak. Nah, untuk awal ini, assume user langsung aktif. Jd returnnya sekedar informasi user telah terdaftar. Silakan login. Gituh. Nanti kalau ada mekanisme aktivasi user, baru bisa ada beberapa jenis response sesuai konfigurasi.
